/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Control.AlumnosData;
import Entidades.Alumno;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agustin
 */
public class GestionAlumnos extends javax.swing.JInternalFrame {
    
    AlumnosData alumnos = new AlumnosData(); //Se utilizará para las consultas de la base de datos
    //Se crea el modelo de la tabla, y se reemplaza el valor de celda editable a falso
    private DefaultTableModel modeloTabla = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    /**
     * Creates new form GestionAlumnos
     */
    public GestionAlumnos() {
        initComponents();
        columnaAlumnos();
        cargarAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpGestorBotones = new javax.swing.JPanel();
        jbInsertar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbAltaLogica = new javax.swing.JButton();
        jbBajaLogica = new javax.swing.JButton();
        jpMostrar = new javax.swing.JPanel();
        jspTabla = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        lTodosLosAlumnos = new javax.swing.JLabel();
        jbActualizarTabla = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jlBuscar = new javax.swing.JLabel();
        lbGestionAlumnos = new javax.swing.JLabel();
        jpAlumnos = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jlApellido = new javax.swing.JLabel();
        jtfApellido = new javax.swing.JTextField();
        jlDNI = new javax.swing.JLabel();
        jtfDNI = new javax.swing.JTextField();
        jlFechaDeNacimiento = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jtbEstado = new javax.swing.JToggleButton();
        jlIDAlumno = new javax.swing.JLabel();
        jtfIDAlumno = new javax.swing.JTextField();
        jlInsertarAlumno = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jdcFechaDeNacimiento = new com.toedter.calendar.JDateChooser();

        jpGestorBotones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbInsertar.setBackground(new java.awt.Color(0, 255, 102));
        jbInsertar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbInsertar.setText("INSERTAR");
        jbInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInsertarActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(0, 204, 204));
        jbActualizar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbActualizar.setText("ACTUALIZAR");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(255, 51, 51));
        jbBorrar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbBorrar.setText("BORRAR");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAltaLogica.setBackground(new java.awt.Color(153, 255, 51));
        jbAltaLogica.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbAltaLogica.setText("ALTA LÓGICA");
        jbAltaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaLogicaActionPerformed(evt);
            }
        });

        jbBajaLogica.setBackground(new java.awt.Color(255, 204, 0));
        jbBajaLogica.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbBajaLogica.setText("BAJA LÓGICA");
        jbBajaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaLogicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGestorBotonesLayout = new javax.swing.GroupLayout(jpGestorBotones);
        jpGestorBotones.setLayout(jpGestorBotonesLayout);
        jpGestorBotonesLayout.setHorizontalGroup(
            jpGestorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGestorBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbActualizar)
                .addGap(20, 20, 20)
                .addGroup(jpGestorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAltaLogica)
                    .addComponent(jbBajaLogica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBorrar)
                .addContainerGap())
        );
        jpGestorBotonesLayout.setVerticalGroup(
            jpGestorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGestorBotonesLayout.createSequentialGroup()
                .addGroup(jpGestorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpGestorBotonesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpGestorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbInsertar)
                            .addComponent(jbActualizar)
                            .addComponent(jbBorrar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpGestorBotonesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbAltaLogica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbBajaLogica)))
                .addContainerGap())
        );

        jpMostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtTabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaMouseClicked(evt);
            }
        });
        jspTabla.setViewportView(jtTabla);

        lTodosLosAlumnos.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lTodosLosAlumnos.setText("Todos los alumnos");

        jbActualizarTabla.setBackground(new java.awt.Color(0, 204, 204));
        jbActualizarTabla.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbActualizarTabla.setText("ACTUALIZAR TABLA");
        jbActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarTablaActionPerformed(evt);
            }
        });

        jtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarActionPerformed(evt);
            }
        });

        jlBuscar.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jlBuscar.setText("Buscar");

        javax.swing.GroupLayout jpMostrarLayout = new javax.swing.GroupLayout(jpMostrar);
        jpMostrar.setLayout(jpMostrarLayout);
        jpMostrarLayout.setHorizontalGroup(
            jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMostrarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTodosLosAlumnos)
                    .addGroup(jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jspTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpMostrarLayout.createSequentialGroup()
                            .addComponent(jbActualizarTabla)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlBuscar)
                                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(25, 25, 25))
        );
        jpMostrarLayout.setVerticalGroup(
            jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMostrarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lTodosLosAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpMostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbActualizarTabla)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbGestionAlumnos.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbGestionAlumnos.setText("GESTION DE ALUMNOS");

        jpAlumnos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlNombre.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlNombre.setText("Nombre:");

        jlApellido.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlApellido.setText("Apellido:");

        jlDNI.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlDNI.setText("DNI:");

        jlFechaDeNacimiento.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlFechaDeNacimiento.setText("Fecha de nacimiento:");

        jlEstado.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlEstado.setText("Estado:");

        jtbEstado.setBackground(java.awt.Color.green);
        jtbEstado.setSelected(true);
        jtbEstado.setText("Activo");
        jtbEstado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtbEstadoStateChanged(evt);
            }
        });
        jtbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbEstadoActionPerformed(evt);
            }
        });

        jlIDAlumno.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jlIDAlumno.setText("ID Alumno:");

        jtfIDAlumno.setEditable(false);

        jlInsertarAlumno.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jlInsertarAlumno.setText("Insertar Alumno:");

        jbNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jbNuevo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jbNuevo.setText("NUEVO");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAlumnosLayout = new javax.swing.GroupLayout(jpAlumnos);
        jpAlumnos.setLayout(jpAlumnosLayout);
        jpAlumnosLayout.setHorizontalGroup(
            jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAlumnosLayout.createSequentialGroup()
                        .addComponent(jlInsertarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlIDAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAlumnosLayout.createSequentialGroup()
                        .addComponent(jlNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombre)
                        .addGap(18, 18, 18)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEstado)
                            .addComponent(jlDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jpAlumnosLayout.createSequentialGroup()
                            .addComponent(jlFechaDeNacimiento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jdcFechaDeNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jpAlumnosLayout.createSequentialGroup()
                            .addComponent(jlApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jpAlumnosLayout.setVerticalGroup(
            jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jlInsertarAlumno)
                    .addComponent(jlIDAlumno)
                    .addComponent(jtfIDAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAlumnosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlApellido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFechaDeNacimiento)
                            .addComponent(jdcFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAlumnosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDNI))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlEstado)
                            .addComponent(jtbEstado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jpGestorBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbGestionAlumnos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbGestionAlumnos)
                .addGap(10, 10, 10)
                .addComponent(jpMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpGestorBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBajaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaLogicaActionPerformed
        //Se realiza las corroboraciones correspondientes para dar de baja lógica al Alumno
        //El ID se utilizará para buscar alumno y para actualizar
        int ID = Integer.parseInt(jtfIDAlumno.getText());

        //Se verificará si el alumno existe o no, caso contrario brinda el error
        Alumno a = alumnos.buscarAlumno(ID);

        if (a != null) {
            JOptionPane.showMessageDialog(null, "Se ha dado de baja al alumno con éxito");
            alumnos.darDeBaja(a.getDni());
        } else {
            JOptionPane.showMessageDialog(null, "No se puede dar de baja un alumno que ha sido eliminado");
        }
    }//GEN-LAST:event_jbBajaLogicaActionPerformed

    private void jtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        //Se limpia todos los atributos para insertar un nuevo Alumno
        jtfNombre.setText("");
        jtfApellido.setText("");
        jtfDNI.setText("");
        jtfIDAlumno.setText("");
        jtbEstado.setSelected(true);
        jdcFechaDeNacimiento.setDate(null);
        //Se habilita la posibilidad de Insertar Alumnos a la base de datos
        jbInsertar.setEnabled(true);
        //Se inhabilita la posibilidad de Actualizar Alumnos a la base de datos
        jbActualizar.setEnabled(false);        
        //Se habilita la posiblidad de cambiar de estado lógico
        //botonEstado(true);

    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbEstadoActionPerformed

    }//GEN-LAST:event_jtbEstadoActionPerformed

    private void jtbEstadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtbEstadoStateChanged
        //Cambiar estado en Activo o Inactivo
        if (jtbEstado.isSelected()) {
            jtbEstado.setText("Activo");
            jtbEstado.setBackground(Color.green);
        } else {
            jtbEstado.setText("Inactivo");
            jtbEstado.setBackground(Color.red);
        }
    }//GEN-LAST:event_jtbEstadoStateChanged

    private void jtTablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaMouseClicked
        cargarInformacion(evt.getPoint());
    }//GEN-LAST:event_jtTablaMouseClicked

    private void jbInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInsertarActionPerformed
        //Se realizará las comprobaciones correspondientes para Insertar un nuevo Alumno        
        if (ingresarAlumno() != null) {
            JOptionPane.showMessageDialog(null, "Se ha cargado el alumno con éxito");
            alumnos.cargarAlumno(ingresarAlumno());
        }
        
    }//GEN-LAST:event_jbInsertarActionPerformed

    private void jbActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarTablaActionPerformed
        //Se encarga de actualizar la tabla
        cargarAlumnos();
    }//GEN-LAST:event_jbActualizarTablaActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        //Se realizará las comprobaciones correspondientes para Actualizar un Alumno
        try {
            Alumno a = ingresarAlumno();

            //El ID se utilizará para buscar alumno y para actualizarlo
            int ID = Integer.parseInt(jtfIDAlumno.getText());

            //Se verificará si el alumno existe o no, caso contrario brinda el error
            Alumno aAnterior = alumnos.buscarAlumno(ID);

            if (a != null && aAnterior != null) {
                a.setId(ID); //Toma el Id del alumno, caso contrario no podrá actualizarlo
                JOptionPane.showMessageDialog(null, "Se ha actualizado al alumno con éxito");
                alumnos.actualizarAlumno(a);
            } else if (aAnterior == null) {
                JOptionPane.showMessageDialog(null, "No se puede actualizar un alumno que ha sido eliminado");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No hay alumno seleccionado para actualizar");
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        //Borra el alumno seleccionado por el ID
        try {
            
            int ID = Integer.parseInt(jtfIDAlumno.getText());
            Alumno alumnoEliminar = alumnos.buscarAlumno(ID);
            
            if (alumnoEliminar != null) {
                alumnos.borrarAlumno(alumnoEliminar.getDni()); //Se utiliza el dni para eliminar
                JOptionPane.showMessageDialog(null, "Se ha eliminado el alumno con éxito");
            } else {
                JOptionPane.showMessageDialog(null, "No existe este alumno, no pudo llevarse a cabo la acción");
            }
                
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,"El casillero ID está vacío, selecciona el alumno a eliminar");
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbAltaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaLogicaActionPerformed
        //Se realiza las corroboraciones correspondientes para dar de alta lógica al Alumno
        //El ID se utilizará para buscar alumno y para actualizar
        int ID = Integer.parseInt(jtfIDAlumno.getText());

        //Se verificará si el alumno existe o no, caso contrario brinda el error
        Alumno a = alumnos.buscarAlumno(ID);

        if (a != null) {
            JOptionPane.showMessageDialog(null, "Se ha dado de alta al alumno con éxito");
            alumnos.darDeAlta(a.getDni());
        } else {
            JOptionPane.showMessageDialog(null, "No se puede dar de alta un alumno que ha sido eliminado");
        }
    }//GEN-LAST:event_jbAltaLogicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbActualizarTabla;
    private javax.swing.JButton jbAltaLogica;
    private javax.swing.JButton jbBajaLogica;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbInsertar;
    private javax.swing.JButton jbNuevo;
    private com.toedter.calendar.JDateChooser jdcFechaDeNacimiento;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlBuscar;
    private javax.swing.JLabel jlDNI;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlFechaDeNacimiento;
    private javax.swing.JLabel jlIDAlumno;
    private javax.swing.JLabel jlInsertarAlumno;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JPanel jpAlumnos;
    private javax.swing.JPanel jpGestorBotones;
    private javax.swing.JPanel jpMostrar;
    private javax.swing.JScrollPane jspTabla;
    private javax.swing.JTable jtTabla;
    private javax.swing.JToggleButton jtbEstado;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfBuscar;
    private javax.swing.JTextField jtfDNI;
    private javax.swing.JTextField jtfIDAlumno;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JLabel lTodosLosAlumnos;
    private javax.swing.JLabel lbGestionAlumnos;
    // End of variables declaration//GEN-END:variables

    //Se agrega las columnas con sus nombres correspondientes a la tabla
    private void columnaAlumnos() {
        modeloTabla.addColumn("ID alumno");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Fecha de nacimiento");
        modeloTabla.addColumn("Estado");
        jtTabla.setModel(modeloTabla);
    }
    
    //Se agregan todos los alumnos de la base de datos
    private void cargarAlumnos() {
        limpiarTabla();
        Iterator<Alumno> iterar = alumnos.mostrarAlumnos().iterator();
        while (iterar.hasNext()) {
            Alumno a = iterar.next();
                modeloTabla.addRow(new Object[]{a.getId(), a.getNombre(), a.getApellido(),
                    a.getDni(), a.getFechaNacimiento(), estadoAlumnoParaTabla(a.isEstado())});
        }
    }
    
    //Limpia la tabla
    private void limpiarTabla() {

        int f = modeloTabla.getRowCount() - 1; //total de filas (-1 para recorrer for)
        for (int i = f; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }
    
    //Tomar los datos de la tabla y pasarlo a los datos editables debajo
    private void cargarInformacion(Point evento) 
    {
        
        int seleccionFila = jtTabla.rowAtPoint(evento); 
        /*
         El Point evento es el parametro que se tomará de distintos eventos, el Point muestra la 
        ubicación de la fila seleccionada, para tomar esa información.
        seleccionFila es el valor de la fila tomada
        */
        
        int columnaID = 0; //En primera instancia la columna ID alumno es 0, pero puede modificarse durante la ejecución
        
        //con el for podemos saber cuál es la columna con el nombre ID alumno iterando sobre todas las columnas y consultando su nombre   
        for (int i = 0; i < jtTabla.getColumnCount(); i++) {           
            if (jtTabla.getColumnName(i).equals("ID alumno")) {
                columnaID = i;
            }     
        }
        
        //Se busca alumno seleccionado por el ID alumno
        int ID_Alumno = (int)(jtTabla.getValueAt(seleccionFila, columnaID));
        
        try {
            
            //Realiza la busqueda del alumno con el ID
            Alumno alumnoSelec = alumnos.buscarAlumno(ID_Alumno);

            //Se completa lo seleccionado en la tabla en cada atributo:
            jtfNombre.setText(alumnoSelec.getNombre());
            jtfApellido.setText(alumnoSelec.getApellido());
            jtfIDAlumno.setText(String.valueOf(alumnoSelec.getId()));
            jtfDNI.setText(String.valueOf(alumnoSelec.getDni()));
            jtbEstado.setSelected(alumnoSelec.isEstado());
            //Se realiza la conversión de LocalDate a Date
            Date fechaDate = Date.from(alumnoSelec.getFechaNacimiento().atStartOfDay(ZoneId.systemDefault()).toInstant());
            jdcFechaDeNacimiento.setDate(fechaDate);

            //Se inhabilita la posibilidad de Insertar nuevo ALumno, debe colocarse la opción "Nuevo"
            jbInsertar.setEnabled(false);
            
            //Se inhabilita la posiblidad de cambiar de estado lógico
            //botonEstado(false);
            
        } catch (NullPointerException e) {            
            JOptionPane.showMessageDialog(null, "No puede cargarse información de un alumno que no existe");            
        }
            
              
        
        
    }
    
    //Funcion que determina el estado del boton jtbEstado, si está presionado devuelve true, si no, false
    private boolean estadoAlumno() {        
        return jtbEstado.isSelected();     
    }
    
    //Se crea un string en base al estado del Alumno, para mostrarlo en la tabla
    private String estadoAlumnoParaTabla(boolean estado) {
        
        if (estado) {
            return "activo";
        } else {
            return "inactivo";
        }      
    }
    
    //Se utilizará para insertar y actualizar alumnos, es una verificación por cada casillero
    private Alumno ingresarAlumno() {
        try {

            //Se utilizará para que, al sumar cualquier error, no le permita Insertar a la BD el alumno
            int error = 0;
            String nombre = jtfNombre.getText();

            //Varchar = 100, si es más largo el nombre, tira el error
            if (nombre.length() > 100) {
                JOptionPane.showMessageDialog(null, "El nombre se excede de la cantidad de caracteres, ingrese uno menor a 100 caracteres");
                error++;
            } else if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No puede estar vacío el casillero Nombre");
                error++;
            }
            String apellido = jtfApellido.getText();

            //Varchar = 100 si es más largo el apellido, tira el error
            if (apellido.length() > 100) {
                JOptionPane.showMessageDialog(null, "El apellido se excede de la cantidad de caracteres, ingrese uno menor a 100 caracteres");
                error++;
            } else if (apellido.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No puede estar vacío el casillero Apellido");
                error++;
            }

            int DNI = Integer.parseInt(jtfDNI.getText());
            //Si se coloca otro valor que no es númerico entero, da excepción NumberFormatException

            //INT = 11, si se excede la cantidad de digitos tira error
            if (String.valueOf(DNI).length() > 11) {
                JOptionPane.showMessageDialog(null, "El DNI debe tener como máximo 11 digitos, por favor, corrijalo");
                error++;
            } else if (DNI < 1) {
                JOptionPane.showMessageDialog(null, "El DNI no puede ser 0 o negativo, por favor, corrijalo");
            }
            
            //Se utilizará como comprobación de que si se encuentra un DNI en la BD igual al colocado en pantalla, brindará error
            Iterator<Alumno> iterar = alumnos.mostrarAlumnos().iterator();
            while (iterar.hasNext()) {
                Alumno a = iterar.next();
                /*Se realiza corroboracion del ID que ya esté seleccionado debido a que
                * si se necesita actualizar se da por acentado que el DNI va a ser el mismo
                * que el que se desea actualizar
                */
                if (a.getDni() == DNI && a.getId() != Integer.parseInt(jtfIDAlumno.getText())) {
                    JOptionPane.showMessageDialog(null, "Este DNI ya existe, por favor, corrijalo");
                    error++;
                }
            }

            //El estado del alumno
            boolean estado = estadoAlumno();

            //Toma la fecha de nacimiento del Alumno como Date, no lo podemos manipular en el sistema actual, debemos cambiarlo a LocalDate
            Date fechaNacimientoDate = jdcFechaDeNacimiento.getDate();

            //Se crea de antemano FechaDeNacimiento de tipo LocalDate (el que se utilizará en alumno
            LocalDate fechaNacimiento = null;
            if (fechaNacimientoDate == null) {
                JOptionPane.showMessageDialog(null, "Debe colocar una fecha de nacimiento al alumno");
                error++;
            } else { //Es para evitar la excepcion de objeto null

                //Se pasa de Date a LocalDate para tratarlo en nuestro sistema
                fechaNacimiento = fechaNacimientoDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                //Se crea un formato similar a la base de datos año-mes-dia
                DateTimeFormatter formatoLocalDate = DateTimeFormatter.ofPattern("yyyy-MM-dd");

                //Se coloca el formato en el LocalDate que será cargado a la fecha de nacimiento del Alumno
                fechaNacimiento.format(formatoLocalDate);

            }

            if (error == 0) {
                Alumno a = new Alumno(DNI, nombre, apellido, fechaNacimiento, estado); //Se crea el alumno
                return a;
                
            } else {
                JOptionPane.showMessageDialog(null, "Debe atender a los errores previamente mencionados");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Debe colocar un formato válido, númerico, en DNI");
        }
        return null;
    }
    
    /*El botón de estado al ser un toggle button puede seleccionarse o deseleccionarse, con esta funcion
    * se hará posible mantener un estado sin inhabilitarlo, pero que tampoco pueda cambiarse,
    * esto será útil cuando se necesita actualizar un Alumno, debido a que para actualizar su estado
    * tenemos las funciones correspondientes de alta y baja lógica.
    */
    /*private void botonEstado(boolean activo) {
        
        if (activo) {
            jtbEstado.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    //Al estar vacío, nos da la herramienta de cambiar de estado
                    
                }
            });
        } else {
            boolean estadoLogico = estadoAlumno();
            jtbEstado.addItemListener(new ItemListener() {
                @Override
                public void itemStateChanged(ItemEvent e) {
                    //Toma el valor actual, no podrá modificarse al hacer click
                    jtbEstado.setSelected(false);
                }
            });
        }

        
    }*/



}
