
package Vista;

import Control.MateriasData;
import javax.swing.JOptionPane;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



public class GestionMaterias extends javax.swing.JInternalFrame {
    public static MateriasData materias = new MateriasData();
    private boolean estado;//variable para el constructor materia
    private boolean estadoA;
    private DefaultTableModel modelo = new DefaultTableModel(){
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
    
    /**
     * Creates new form GestionMaterias
     */
    public GestionMaterias() {
        initComponents();
        armarTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstados = new javax.swing.ButtonGroup();
        bgEstadosA = new javax.swing.ButtonGroup();
        jpPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbAño = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jbSubir = new javax.swing.JButton();
        jlbEstado = new javax.swing.JLabel();
        jrbAlta = new javax.swing.JRadioButton();
        jrbBaja = new javax.swing.JRadioButton();
        jbNuevo = new javax.swing.JButton();
        jpPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMaterias = new javax.swing.JTable();
        jlbIngreseID = new javax.swing.JLabel();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jbBorrar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jlbNombreA = new javax.swing.JLabel();
        jlbAñoA = new javax.swing.JLabel();
        jlbEstadoA = new javax.swing.JLabel();
        txtNombreA = new javax.swing.JTextField();
        txtAñoA = new javax.swing.JTextField();
        jrbAltaA = new javax.swing.JRadioButton();
        jrbBajaA = new javax.swing.JRadioButton();
        jbSalir = new javax.swing.JButton();

        jpPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 4, true));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Ingrese los datos de la materia");

        jlbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbNombre.setText("Nombre");

        jlbAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbAño.setText("Año");

        jbSubir.setBackground(new java.awt.Color(153, 255, 102));
        jbSubir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSubir.setForeground(new java.awt.Color(0, 0, 153));
        jbSubir.setText("Insertar");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jlbEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbEstado.setText("Estado");

        bgEstados.add(jrbAlta);
        jrbAlta.setText("Alta");
        jrbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaActionPerformed(evt);
            }
        });

        bgEstados.add(jrbBaja);
        jrbBaja.setText("Baja");
        jrbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBajaActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(204, 204, 204));
        jbNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbNuevo.setForeground(new java.awt.Color(0, 0, 153));
        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelLayout = new javax.swing.GroupLayout(jpPanel);
        jpPanel.setLayout(jpPanelLayout);
        jpPanelLayout.setHorizontalGroup(
            jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpPanelLayout.createSequentialGroup()
                        .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbNombre)
                            .addComponent(jlbAño))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(jpPanelLayout.createSequentialGroup()
                        .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPanelLayout.createSequentialGroup()
                                .addComponent(jlbEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbAlta))
                            .addGroup(jpPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
                            .addGroup(jpPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbBaja)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanelLayout.setVerticalGroup(
            jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEstado)
                    .addComponent(jrbAlta)
                    .addComponent(jrbBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jpPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 4, true));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Materias");

        jtTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTablaMaterias);

        jlbIngreseID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlbIngreseID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbIngreseID.setText("id de la materia que quiera modificar:");

        jbAlta.setBackground(new java.awt.Color(153, 255, 153));
        jbAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAlta.setForeground(new java.awt.Color(0, 0, 153));
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(102, 255, 255));
        jbBaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBaja.setForeground(new java.awt.Color(0, 0, 153));
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(255, 153, 102));
        jbBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(0, 0, 153));
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbActualizar.setBackground(new java.awt.Color(51, 153, 255));
        jbActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(0, 0, 153));
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jlbNombreA.setText("Nombre");

        jlbAñoA.setText("Año");

        jlbEstadoA.setText("Estado");

        jrbAltaA.setText("Alta");
        jrbAltaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaAActionPerformed(evt);
            }
        });

        jrbBajaA.setText("Baja");
        jrbBajaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBajaAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanel2Layout = new javax.swing.GroupLayout(jpPanel2);
        jpPanel2.setLayout(jpPanel2Layout);
        jpPanel2Layout.setHorizontalGroup(
            jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jlbIngreseID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbBaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbNombreA)
                            .addComponent(jlbAñoA)
                            .addComponent(jlbEstadoA)
                            .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAñoA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPanel2Layout.createSequentialGroup()
                        .addComponent(jrbAltaA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbBajaA)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPanel2Layout.setVerticalGroup(
            jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbIngreseID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPanel2Layout.createSequentialGroup()
                        .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbNombreA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbAñoA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAñoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbEstadoA)
                        .addGap(1, 1, 1)
                        .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jrbAltaA)
                            .addComponent(jrbBajaA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jbSalir.setBackground(new java.awt.Color(255, 0, 51));
        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(0, 0, 153));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        validarCampos();
        cargarTabla();
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        try{
            String nombre=txtNombreA.getText();
            int año = Integer.parseInt(txtAñoA.getText());
            if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre");
            }else if(txtAñoA.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese un año");
            }else{
                
            Materia m = new Materia(nombre, año, estadoA);
            m.setId_materia(Integer.parseInt(txtID.getText()));//parseamos el valor id y le asignamos al object Materia
            materias.actualizarMateria(m);
            }
            
        }catch(java.lang.NumberFormatException error){
            JOptionPane.showMessageDialog(null, error.getMessage());
        }
        cargarTabla();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBajaActionPerformed
        // TODO add your handling code here:
        estado = false;//le asignamos el valor correspondiente a la variable booleana estado
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_jrbBajaActionPerformed

    private void jrbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaActionPerformed
        // TODO add your handling code here:
        estado = true;//le asignamos el valor correspondiente a la variable booleana estado
        System.out.println(evt.getActionCommand());
        
    }//GEN-LAST:event_jrbAltaActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
         try{
         int id = Integer.parseInt(txtID.getText());
         materias.darDeAlta(id);
         cargarTabla();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
        }
       
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
         try{
        int id = Integer.parseInt(txtID.getText());
        materias.darDeBaja(id);
        cargarTabla();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
        }
        
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        txtNombre.setText("");
        txtAño.setText("");
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
         try{
        int id = Integer.parseInt(txtID.getText());
        materias.borrarMateria(id);
        cargarTabla();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
        }
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jrbAltaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaAActionPerformed
        // TODO add your handling code here:
        estadoA= true;
    }//GEN-LAST:event_jrbAltaAActionPerformed

    private void jrbBajaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBajaAActionPerformed
        // TODO add your handling code here:
        estadoA = false;
    }//GEN-LAST:event_jrbBajaAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstados;
    private javax.swing.ButtonGroup bgEstadosA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JLabel jlbAño;
    private javax.swing.JLabel jlbAñoA;
    private javax.swing.JLabel jlbEstado;
    private javax.swing.JLabel jlbEstadoA;
    private javax.swing.JLabel jlbIngreseID;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JLabel jlbNombreA;
    private javax.swing.JPanel jpPanel;
    private javax.swing.JPanel jpPanel2;
    private javax.swing.JRadioButton jrbAlta;
    private javax.swing.JRadioButton jrbAltaA;
    private javax.swing.JRadioButton jrbBaja;
    private javax.swing.JRadioButton jrbBajaA;
    private javax.swing.JTable jtTablaMaterias;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtAñoA;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreA;
    // End of variables declaration//GEN-END:variables

    private void armarTabla(){
        modelo.addColumn("ID_MATERIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("AÑO");
        modelo.addColumn("ESTADO");
        jtTablaMaterias.setModel(modelo);
    }
    
    private void cargarTabla(){
        borrarTabla();
        for (Materia m : materias.mostrarMaterias()){
            modelo.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAño(), m.isEstado()});
        }
        
    }
    
    /*private void borrarTabla(){
        int ind= modelo.getRowCount()-1;
        for (int i = ind; i <= 0; i--) {
            modelo.removeRow(i);
        }
    }*/
    private void borrarTabla(){
    int ind = modelo.getRowCount() -1 ;
    for (int i = ind; i >= 0; i--) {
     modelo.removeRow(i);
        }
    }
    
    private void validarCampos(){
    
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted no ha ingresado un Nombre!!!!");
        } else if (txtAño.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted no ha ingresado el año!!!!");
        }else{
            try {
                //parseamos y guardamos los datos en las varibales
                String nombre = txtNombre.getText();
                int año = Integer.parseInt(txtAño.getText());
                //creamos la materia
                Materia m = new Materia(nombre, año, estado);
                //lo cargamos a la base de datos mediante el MateriasData Static de Gestion
                materias.cargarMateria(m);
            } catch (java.lang.NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese el año en el formato correcto!!");
            }
        }
    }
    
}
