
package Vista;

import Control.MateriasData;
import Control.*;
import Vista.GestionAlumnos;
// import Vista.GestionInscripcion;
import Vista.GestionMaterias;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JInternalFrame;


public class Gestion extends javax.swing.JFrame {
    
    private Connection con = null;
    /**
     * Creates new form Gestion
     */
    public Gestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmiCargarAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmiGestionMateria = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmiGestionInscripcion = new javax.swing.JMenuItem();
        jmNotas = new javax.swing.JMenu();
        jmiCargarNotas = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 700));

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");

        jmiCargarAlumno.setText("Gestion");
        jmiCargarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmiCargarAlumno);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmiGestionMateria.setText("Gestionar Materias");
        jmiGestionMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmiGestionMateria);

        jMenuBar1.add(jmMateria);

        jmInscripcion.setText("Inscripcion");

        jmiGestionInscripcion.setText("Gestion Inscripcion");
        jmiGestionInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionInscripcionActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiGestionInscripcion);

        jMenuBar1.add(jmInscripcion);

        jmNotas.setText("Notas");

        jmiCargarNotas.setText("Cargar Notas");
        jmiCargarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCargarNotasActionPerformed(evt);
            }
        });
        jmNotas.add(jmiCargarNotas);

        jMenuBar1.add(jmNotas);

        jmSalir.setText("Salir");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionMateriaActionPerformed
        
        
        //Primero intenta si permite conectarse a la base de datos
        con = MiConexion.getConexion();

        if (con != null) {
            GestionMaterias gm = new GestionMaterias();
            cargarVentana(gm);
        }
    }//GEN-LAST:event_jmiGestionMateriaActionPerformed

    private void jmiCargarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarAlumnoActionPerformed
        
        //Primero intenta si permite conectarse a la base de datos
        con = MiConexion.getConexion();

        if (con != null) {
            GestionAlumnos ga = new GestionAlumnos();
            cargarVentana(ga);
        } 
    }//GEN-LAST:event_jmiCargarAlumnoActionPerformed

    private void jmiGestionInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionInscripcionActionPerformed
        
        //Primero intenta si permite conectarse a la base de datos
        con = MiConexion.getConexion();

        if (con != null) {
            GestionInscripcion gi = new GestionInscripcion();
            cargarVentana(gi);
        }
                
    }//GEN-LAST:event_jmiGestionInscripcionActionPerformed

    private void jmiCargarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCargarNotasActionPerformed
        

        //Primero intenta si permite conectarse a la base de datos
        con = MiConexion.getConexion();

        if (con != null) {
            GestionNotas n = new GestionNotas();
            cargarVentana(n);
        }
       
    }//GEN-LAST:event_jmiCargarNotasActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(null, "¿Estás seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if (salir == 0) {
            JOptionPane.showMessageDialog(null, "¡Gracias por utilizar nuestro servicio!");
            System.exit(0);
        }
    }//GEN-LAST:event_jmiSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMateria;
    private javax.swing.JMenu jmNotas;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiCargarAlumno;
    private javax.swing.JMenuItem jmiCargarNotas;
    private javax.swing.JMenuItem jmiGestionInscripcion;
    private javax.swing.JMenuItem jmiGestionMateria;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables

    private void cargarVentana(JInternalFrame ventana) {
        
        
        
            jdpEscritorio.removeAll();
            jdpEscritorio.repaint();
            ventana.setVisible(true);
            jdpEscritorio.add(ventana);
            jdpEscritorio.moveToFront(ventana);
        
        
    }


}
