
package Vista;

import Control.MateriasData;
import javax.swing.JOptionPane;
import Entidades.Materia;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



public class GestionMaterias extends javax.swing.JInternalFrame {
    public static MateriasData materias = new MateriasData();
    private boolean estado;//variable para el constructor materia
    private boolean estadoA;
    private DefaultTableModel modelo = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int fila, int columna){ 
        return false;
    }
    };
    
    /**
     * Creates new form GestionMaterias
     */
    public GestionMaterias() {
        initComponents();
        armarTabla();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEstados = new javax.swing.ButtonGroup();
        bgEstadosA = new javax.swing.ButtonGroup();
        jpPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlbNombre = new javax.swing.JLabel();
        jlbAño = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jbSubir = new javax.swing.JButton();
        jlbEstado = new javax.swing.JLabel();
        jrbAlta = new javax.swing.JRadioButton();
        jrbBaja = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbActualizar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jpPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaMaterias = new javax.swing.JTable();
        jbAlta = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jpPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 4, true));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("Ingrese los datos de la materia");

        jlbNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbNombre.setText("Nombre");

        jlbAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbAño.setText("Año");

        jbSubir.setBackground(new java.awt.Color(153, 255, 102));
        jbSubir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSubir.setForeground(new java.awt.Color(0, 0, 153));
        jbSubir.setText("Insertar");
        jbSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubirActionPerformed(evt);
            }
        });

        jlbEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbEstado.setText("Estado");

        bgEstados.add(jrbAlta);
        jrbAlta.setText("Alta");
        jrbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAltaActionPerformed(evt);
            }
        });

        bgEstados.add(jrbBaja);
        jrbBaja.setText("Baja");
        jrbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbBajaActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Id:");

        jbActualizar.setBackground(new java.awt.Color(51, 153, 255));
        jbActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbActualizar.setForeground(new java.awt.Color(0, 0, 153));
        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(255, 0, 51));
        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(0, 0, 153));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPanelLayout = new javax.swing.GroupLayout(jpPanel);
        jpPanel.setLayout(jpPanelLayout);
        jpPanelLayout.setHorizontalGroup(
            jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpPanelLayout.createSequentialGroup()
                        .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanelLayout.createSequentialGroup()
                        .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPanelLayout.createSequentialGroup()
                                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbNombre)
                                    .addComponent(jlbAño))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpPanelLayout.createSequentialGroup()
                                .addComponent(jlbEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbAlta)
                                .addGap(7, 7, 7)
                                .addComponent(jrbBaja)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPanelLayout.setVerticalGroup(
            jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbEstado)
                    .addComponent(jrbAlta)
                    .addComponent(jrbBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jpPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 4, true));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setText("Materias");

        jtTablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaMaterias);

        jbAlta.setBackground(new java.awt.Color(153, 255, 153));
        jbAlta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbAlta.setForeground(new java.awt.Color(0, 0, 153));
        jbAlta.setText("Alta");
        jbAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(102, 255, 255));
        jbBaja.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBaja.setForeground(new java.awt.Color(0, 0, 153));
        jbBaja.setText("Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        jbBorrar.setBackground(new java.awt.Color(255, 153, 102));
        jbBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbBorrar.setForeground(new java.awt.Color(0, 0, 153));
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Seleccione la fila que desea actualizar");

        javax.swing.GroupLayout jpPanel2Layout = new javax.swing.GroupLayout(jpPanel2);
        jpPanel2.setLayout(jpPanel2Layout);
        jpPanel2Layout.setHorizontalGroup(
            jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jpPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jpPanel2Layout.setVerticalGroup(
            jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        validarCampos();
        cargarTabla();
    }//GEN-LAST:event_jbSubirActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        try{
            int fila = jtTablaMaterias.getSelectedRow();
            String nombre = txtNombre.getText();
            int año = Integer.parseInt(txtAño.getText());
            if(txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese un nombre");
            }else if(txtAño.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Ingrese un año");
            }else{
                
            Materia m = new Materia(nombre, año, estado);
            m.setId_materia(Integer.parseInt(txtID.getText()));//parseamos el valor id y le asignamos al object Materia
            materias.actualizarMateria(m);
            cargarTabla();
           
            }
        }catch(java.lang.NumberFormatException error){
            JOptionPane.showMessageDialog(null, "Le falto ingresar el año!!!");
        }catch(java.lang.ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea modificar");
        }
         vaciarCampos();
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        System.out.println(evt.getActionCommand());
        setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbBajaActionPerformed
        // TODO add your handling code here:
        estado = false;//le asignamos el valor correspondiente a la variable booleana estado
        System.out.println(evt.getActionCommand());
    }//GEN-LAST:event_jrbBajaActionPerformed

    private void jrbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAltaActionPerformed
        // TODO add your handling code here:
        estado = true;//le asignamos el valor correspondiente a la variable booleana estado
        System.out.println(evt.getActionCommand());
        
    }//GEN-LAST:event_jrbAltaActionPerformed

    private void jbAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaActionPerformed
        // TODO add your handling code here:
         try{
         int filaSel= jtTablaMaterias.getSelectedRow();
        String idd = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 0));
        int id = Integer.parseInt(idd);
         materias.darDeAlta(id);
         cargarTabla();
         vaciarCampos();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
            
        }catch(java.lang.ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea modificar");
        }
       
    }//GEN-LAST:event_jbAltaActionPerformed

    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        // TODO add your handling code here:
         try{
        int filaSel= jtTablaMaterias.getSelectedRow();
        String idd = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 0));
        int id = Integer.parseInt(idd);
        materias.darDeBaja(id);
        cargarTabla();
        vaciarCampos();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
            
        }catch(java.lang.ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea modificar");
        }
        
    }//GEN-LAST:event_jbBajaActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
        // TODO add your handling code here:
         try{
        int filaSel= jtTablaMaterias.getSelectedRow();
        String idd = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 0));
        int id = Integer.parseInt(idd);
        materias.borrarMateria(id);
        cargarTabla();
        vaciarCampos();
        }catch(java.lang.NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
            
        }catch(java.lang.ArrayIndexOutOfBoundsException error){
            JOptionPane.showMessageDialog(null, "Seleccione la fila que desea modificar");
        }
        
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jtTablaMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaMateriasMouseClicked
        // TODO add your handling code here:
        int filaSel= jtTablaMaterias.getSelectedRow();
        String id = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 0));
        String nombre = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 1));
        String año = String.valueOf(jtTablaMaterias.getValueAt(filaSel, 2));
        txtAño.setText(año);
        txtNombre.setText(nombre);
        txtID.setText(id);
    }//GEN-LAST:event_jtTablaMateriasMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEstados;
    private javax.swing.ButtonGroup bgEstadosA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbAlta;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbSubir;
    private javax.swing.JLabel jlbAño;
    private javax.swing.JLabel jlbEstado;
    private javax.swing.JLabel jlbNombre;
    private javax.swing.JPanel jpPanel;
    private javax.swing.JPanel jpPanel2;
    private javax.swing.JRadioButton jrbAlta;
    private javax.swing.JRadioButton jrbBaja;
    private javax.swing.JTable jtTablaMaterias;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void armarTabla(){
        modelo.addColumn("ID_MATERIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("AÑO");
        modelo.addColumn("ESTADO");
        jtTablaMaterias.setModel(modelo);
        
    }
    
    private void cargarTabla(){
        borrarTabla();
        for (Materia m : materias.mostrarMaterias()){
            modelo.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAño(), m.isEstado()});
        }
        
    }
    
    private void borrarTabla(){
    int ind = modelo.getRowCount() -1 ;
    for (int i = ind; i >= 0; i--) {
     modelo.removeRow(i);
        }
    }
    
    private void validarCampos(){
    
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted no ha ingresado un Nombre!!!!");
        } else if (txtAño.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Usted no ha ingresado el año!!!!");
        }else{
            try {
                //parseamos y guardamos los datos en las varibales
                String nombre = txtNombre.getText();
                int año = Integer.parseInt(txtAño.getText());
                //creamos la materia
                Materia m = new Materia(nombre, año, estado);
                //lo cargamos a la base de datos mediante el MateriasData Static de Gestion
                materias.cargarMateria(m);
                vaciarCampos();
            } catch (java.lang.NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Ingrese el año en el formato correcto!!");
            }
        }
    }
    private void vaciarCampos(){
        
        txtNombre.setText("");
        txtAño.setText("");
        txtID.setText("");
        bgEstados.clearSelection();
        
    }
}
